name: Repo Metadata Sync

on:
  push:
    branches:
      - main
      - master

jobs:
  repo_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Repo Sync
        uses: iloveitaly/github-actions-metadata-sync@v1
        with:
          # gh secret set GH_PERSONAL_TOKEN --app actions --body TOKEN
          TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
